services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        - SUPABASE_MANAGEMENT_PAT=${SUPABASE_MANAGEMENT_PAT}
        - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
        - CLOUDINARY_CLIENT_ID=${CLOUDINARY_CLIENT_ID}
        - CLOUDINARY_CLIENT_SECRET=${CLOUDINARY_CLIENT_SECRET}
        - NEXT_PUBLIC_SHOW_DETAILED_ERRORS=${NEXT_PUBLIC_SHOW_DETAILED_ERRORS}
    ports:
      - "3000:3000"
    restart: always
    environment:
      - PORT=3000
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_MANAGEMENT_PAT=${SUPABASE_MANAGEMENT_PAT}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_CLIENT_ID=${CLOUDINARY_CLIENT_ID}
      - CLOUDINARY_CLIENT_SECRET=${CLOUDINARY_CLIENT_SECRET}
      - NEXT_PUBLIC_SHOW_DETAILED_ERRORS=${NEXT_PUBLIC_SHOW_DETAILED_ERRORS}
